"""Private bounded Python repository evidence detection."""

from __future__ import annotations

import configparser
import fnmatch
import hashlib
import json
import re
import tomllib
from dataclasses import dataclass
from pathlib import PurePosixPath
from typing import cast

import yaml  # type: ignore[import-untyped]
from packaging.requirements import InvalidRequirement, Requirement
from packaging.specifiers import InvalidSpecifier, SpecifierSet
from packaging.utils import canonicalize_name
from packaging.version import InvalidVersion, Version

from slygentify._scan.contracts import (
    ComponentCandidate as _ComponentCandidate,
)
from slygentify._scan.contracts import (
    DetectionContext,
    DetectionResult,
    EvidenceKey,
    PathCandidate,
    RepositoryView,
)
from slygentify._scan.contracts import (
    DiagnosticCandidate as _DiagnosticCandidate,
)
from slygentify._scan.contracts import (
    EvidenceCandidate as _EvidenceCandidate,
)
from slygentify._scan.contracts import (
    FindingCandidate as _FindingCandidate,
)
from slygentify._scan.contracts import (
    RelationshipCandidate as _RelationshipCandidate,
)
from slygentify._scan.detectors._support import StaticStructureError as _YamlStructureError
from slygentify._scan.detectors._support import decode as _decode
from slygentify._scan.detectors._support import evidence_key as _evidence_key
from slygentify._scan.detectors._support import pointer as _pointer
from slygentify._scan.detectors._support import quoted as _quoted
from slygentify._scan.detectors._support import strict_yaml_document as _yaml_document
from slygentify._scan.paths import descendant_paths as _descendant_paths
from slygentify._scan.paths import nearest_ancestor as _nearest_ancestor
from slygentify._scan.paths import parent as _parent
from slygentify._scan.paths import safe_member as _safe_member
from slygentify.traceability import implements

_PYTHON_TOOLS = {
    "pytest": "pytest",
    "pytest-cov": "coverage",
    "ruff": "ruff",
    "black": "black",
    "flake8": "flake8",
    "pycodestyle": "pycodestyle",
    "mypy": "mypy",
    "pyright": "pyright",
    "tox": "tox",
    "pre-commit": "pre-commit",
}
_PYTHON_FRAMEWORKS = frozenset({"fastapi", "flask", "django", "sqlalchemy", "alembic"})
_TOML_BARE_KEY = re.compile(r"[A-Za-z0-9_-]+")
_CREDENTIAL_ASSIGNMENT = re.compile(
    r"(?i)(?<![A-Za-z0-9_])"
    r"[A-Za-z0-9_]*(?:token|password|passwd|secret|api[_-]?key)[A-Za-z0-9_]*"
    r"\s*=\s*(?P<value>\"[^\"\r\n]*\"|'[^'\r\n]*'|[^\s;&|]+)"
)
_CREDENTIAL_URL = re.compile(r"(?i)https?://[^/\s:@]+:(?P<value>[^/\s@]+)@")


@dataclass(frozen=True, slots=True)
class _RuntimeCandidate:
    value: str
    path: str
    locator: str
    role: str
    evidence_key: EvidenceKey


@dataclass(frozen=True, slots=True)
class _MatrixValue:
    value: str
    locator: str


def _python_evidence(
    source_kind: str,
    path: str,
    locator: str | None,
    observation: str,
    semantic_key: str,
) -> _EvidenceCandidate:
    return _EvidenceCandidate(
        source_kind,
        path,
        locator,
        observation,
        "strict bounded static inspection",
        "python.inspect.v1",
        semantic_key,
    )


def _toml_key(value: str) -> str:
    """Return one key segment in deterministic TOML dotted-key syntax."""

    if _TOML_BARE_KEY.fullmatch(value):
        return value
    return json.dumps(value, ensure_ascii=False).replace("\x7f", r"\u007F")


def _toml_locator(*segments: str, index: int | None = None) -> str:
    """Return an unambiguous TOML dotted-key locator with an optional array index."""

    locator = ".".join(_toml_key(segment) for segment in segments)
    return f"{locator}[{index}]" if index is not None else locator


def _template_path(path: str) -> bool:
    return any("{{" in part and "}}" in part for part in PurePosixPath(path).parts)


def _template_content(data: bytes) -> bool:
    return re.search(rb"{{.*?}}|{%.*?%}", data, flags=re.DOTALL) is not None


def _expression_only(value: str) -> bool:
    return re.fullmatch(r"\s*\$\{\{(?:(?!}}).)*}}\s*", value, flags=re.DOTALL) is not None


def _pip_compile_generated(lines: list[str]) -> bool:
    return any(
        re.fullmatch(
            r"\s*#\s+This file is autogenerated by pip-compile(?:\s+with\b.*)?\s*",
            line,
            flags=re.IGNORECASE,
        )
        is not None
        for line in lines[:10]
    )


def _valid_uv_workspace(value: object) -> bool:
    if not isinstance(value, dict):
        return False
    members = value.get("members", [])
    excludes = value.get("exclude", [])
    return (
        isinstance(members, list)
        and all(isinstance(item, str) for item in members)
        and isinstance(excludes, list)
        and all(isinstance(item, str) for item in excludes)
    )


def _matrix_reference(value: str) -> tuple[str, ...] | None:
    match = re.fullmatch(
        r"\s*\$\{\{\s*matrix\.([A-Za-z0-9_-]+(?:\.[A-Za-z0-9_-]+)*)\s*}}\s*",
        value,
    )
    return tuple(match.group(1).split(".")) if match else None


def _nested_value(value: object, names: tuple[str, ...]) -> object | None:
    current = value
    for name in names:
        if not isinstance(current, dict) or name not in current:
            return None
        current = current[name]
    return current


def _mapping_matches(value: object, pattern: object) -> bool:
    if isinstance(pattern, dict):
        return isinstance(value, dict) and all(
            name in value and _mapping_matches(value[name], expected)
            for name, expected in pattern.items()
        )
    return value == pattern


def _matrix_values(
    matrix: object, reference: tuple[str, ...], prefix: tuple[object, ...]
) -> tuple[_MatrixValue, ...]:
    if not isinstance(matrix, dict) or not reference:
        return ()
    values: list[_MatrixValue] = []
    axis_name, nested = reference[0], reference[1:]
    exclusions = matrix.get("exclude", [])
    if not isinstance(exclusions, list) or any(
        not isinstance(item, dict) or set(item) != {axis_name} for item in exclusions
    ):
        return ()
    axis = matrix.get(axis_name)
    if isinstance(axis, list):
        for index, item in enumerate(axis):
            if any(_mapping_matches(item, exclusion[axis_name]) for exclusion in exclusions):
                continue
            value = _nested_value(item, nested) if nested else item
            if isinstance(value, (str, int, float)) and not isinstance(value, bool):
                values.append(
                    _MatrixValue(str(value), _pointer(*prefix, axis_name, index, *nested))
                )
    includes = matrix.get("include")
    if isinstance(includes, list):
        for index, item in enumerate(includes):
            value = _nested_value(item, reference)
            if isinstance(value, (str, int, float)) and not isinstance(value, bool):
                values.append(
                    _MatrixValue(str(value), _pointer(*prefix, "include", index, *reference))
                )
    return tuple(values)


def _ini_document(data: bytes) -> configparser.ConfigParser:
    parser = configparser.ConfigParser(interpolation=None, strict=True)
    parser.read_string(_decode(data))
    return parser


def _strip_requirement_comment(value: str) -> str:
    quote: str | None = None
    escaped = False
    for index, character in enumerate(value):
        if escaped:
            escaped = False
        elif character == "\\" and quote is not None:
            escaped = True
        elif quote is not None:
            if character == quote:
                quote = None
        elif character in {'"', "'"}:
            quote = character
        elif character == "#" and index > 0 and value[index - 1].isspace():
            return value[:index].rstrip()
    return value


def _contains_literal_credential(command: str) -> bool:
    def is_literal(value: str) -> bool:
        unquoted = value.strip().strip("\"'")
        is_function_call = re.match(r"^[A-Za-z_][A-Za-z0-9_.]*\(", unquoted) is not None
        return (
            bool(unquoted)
            and not is_function_call
            and not any(
                marker in unquoted for marker in ("$", "%", "{", "}", "`", "$(", "{{", "}}")
            )
        )

    return any(
        is_literal(match.group("value")) for match in _CREDENTIAL_ASSIGNMENT.finditer(command)
    ) or any(is_literal(match.group("value")) for match in _CREDENTIAL_URL.finditer(command))


def _checkpoint(view: RepositoryView) -> bool:
    return view.checkpoint()


@implements("REQ020", "REQ021", "REQ022", "REQ023", "REQ024", "REQ041")
def detect_python(view: RepositoryView, context: DetectionContext) -> DetectionResult:
    """Detect Python evidence through the bounded repository view."""

    generic_component_paths = context.generic_component_paths
    evidence: list[_EvidenceCandidate] = []
    components: list[_ComponentCandidate] = []
    findings: list[_FindingCandidate] = []
    diagnostics: list[_DiagnosticCandidate] = []
    relationships: list[_RelationshipCandidate] = []
    paths = view.paths()
    path_set = frozenset(paths)
    path_candidates = view.path_candidates()
    pyprojects: dict[str, tuple[str, dict[str, object]]] = {}
    ini_files: dict[str, configparser.ConfigParser] = {}
    component_keys: dict[str, list[tuple[str, str, str | None, str]]] = {}
    qualified_roots: set[str] = set()
    manager_locks: dict[str, dict[str, list[tuple[str, str, str | None, str]]]] = {}
    runtimes: dict[str, list[_RuntimeCandidate]] = {}
    tools: dict[str, dict[str, list[tuple[str, str, str | None, str]]]] = {}

    def add_evidence(item: _EvidenceCandidate) -> tuple[str, str, str | None, str]:
        evidence.append(item)
        return _evidence_key(item)

    def add_finding(
        code: str,
        classification: str,
        root: str | None,
        summary: str,
        keys: tuple[tuple[str, str, str | None, str], ...],
    ) -> None:
        findings.append(_FindingCandidate(code, classification, root, summary, keys))

    def record_template(path: str) -> None:
        key = add_evidence(
            _python_evidence(
                "template",
                path,
                None,
                "An unrendered template Python manifest is present.",
                f"template-manifest:{path}",
            )
        )
        add_finding(
            "python.template-manifest.unknown",
            "unknown",
            None,
            "An unrendered template Python manifest was not evaluated as a current component.",
            (key,),
        )
        diagnostics.append(
            _DiagnosticCandidate(
                "python.template-manifest-unknown",
                path,
                "An unrendered template manifest was not parsed as current repository metadata. "
                "Next: inspect a rendered project when its concrete Python component should be scanned.",
                False,
                None,
                (key,),
                disposition="limitation",
            )
        )

    def record_manager(
        root: str,
        name: str,
        path: str,
        locator: str | None,
        observation: str,
        *,
        is_lock: bool = False,
    ) -> tuple[str, str, str | None, str]:
        item = _python_evidence(
            "manager", path, locator, observation, f"manager:{root}:{name}:{path}:{locator or ''}"
        )
        key = add_evidence(item)
        if is_lock:
            manager_locks.setdefault(root, {}).setdefault(name, []).append(key)
        add_finding(
            "python.manager.evidence",
            "verified",
            root if root in qualified_roots else None,
            (
                f"{name} manager evidence is present at the repository root."
                if root == "."
                else f"{name} manager evidence is present for {root}."
            ),
            (key,),
        )
        return key

    def record_runtime(
        root: str, value: str, path: str, locator: str, role: str
    ) -> tuple[str, str, str | None, str]:
        item = _python_evidence(
            "runtime",
            path,
            locator,
            "A Python runtime declaration is present.",
            f"runtime:{root}:{path}:{locator}:{value}",
        )
        key = add_evidence(item)
        runtimes.setdefault(root, []).append(_RuntimeCandidate(value, path, locator, role, key))
        add_finding(
            "python.runtime.declaration",
            "verified",
            root,
            (
                f"Python supported range {_quoted(value)} is declared."
                if role == "constraint"
                else f"Python interpreter selection {_quoted(value)} is declared."
            ),
            (key,),
        )
        return key

    def record_tool(
        root: str,
        name: str,
        path: str,
        locator: str | None,
        strength: str = "configuration",
    ) -> None:
        item = _python_evidence(
            "tool-configuration",
            path,
            locator,
            f"{name} {strength} evidence is present.",
            f"tool:{root}:{name}:{path}:{locator or ''}:{strength}",
        )
        key = add_evidence(item)
        if strength == "configuration":
            tools.setdefault(root, {}).setdefault(name, []).append(key)
        add_finding(
            "python.tool.evidence",
            "verified",
            root if root in qualified_roots else None,
            f"{name} has {strength} evidence at {path}.",
            (key,),
        )

    def record_dependency(root: str, raw: str, path: str, locator: str, scope: str) -> None:
        try:
            requirement = Requirement(raw)
        except InvalidRequirement:
            diagnostics.append(
                _DiagnosticCandidate(
                    "python.invalid-requirement",
                    path,
                    f"Requirement at {path} [{locator}] is not valid PEP 508 syntax. "
                    "Next: correct the declaration or remove unsupported pip-only syntax.",
                    True,
                    root,
                    disposition="problem",
                )
            )
            return
        name = canonicalize_name(requirement.name)
        item = _python_evidence(
            "dependency",
            path,
            locator,
            f"Direct Python dependency {name} is declared in {scope}.",
            f"dependency:{root}:{scope}:{name}:{path}:{locator}",
        )
        key = add_evidence(item)
        add_finding(
            "python.dependency.declaration",
            "verified",
            root,
            f"Direct dependency {name} is declared in {scope}.",
            (key,),
        )
        if name in _PYTHON_TOOLS:
            record_tool(root, _PYTHON_TOOLS[name], path, locator, "direct-dependency")
        if name in _PYTHON_FRAMEWORKS:
            add_finding(
                "python.framework.declaration",
                "verified",
                root,
                f"The component directly declares {name}.",
                (key,),
            )

    for path in paths:
        if _checkpoint(view):
            break
        if PurePosixPath(path).name != "pyproject.toml":
            continue
        data = view.read_bytes(path)
        if data is None:
            continue
        root = _parent(path)
        if _template_path(path) or _template_content(data):
            record_template(path)
            continue
        try:
            document = tomllib.loads(_decode(data))
        except (UnicodeError, tomllib.TOMLDecodeError):
            diagnostics.append(
                _DiagnosticCandidate(
                    "python.invalid-manifest",
                    path,
                    f"Python manifest {path} could not be parsed as UTF-8 TOML. "
                    "Next: correct the TOML syntax or encoding and scan again.",
                    True,
                    root,
                    disposition="problem",
                )
            )
            continue
        pyprojects[root] = (path, cast(dict[str, object], document))
        tool_value = document.get("tool")
        tool = cast(dict[str, object], tool_value) if isinstance(tool_value, dict) else {}
        uv_value = tool.get("uv")
        uv_workspace = uv_value.get("workspace") if isinstance(uv_value, dict) else None
        other_qualifier = any(
            isinstance(value, dict)
            for value in (document.get("project"), document.get("build-system"), tool.get("poetry"))
        )
        if (
            isinstance(uv_workspace, dict)
            and not _valid_uv_workspace(uv_workspace)
            and not other_qualifier
        ):
            diagnostics.append(
                _DiagnosticCandidate(
                    "python.invalid-workspace",
                    path,
                    "uv workspace members and exclusions must be lists of literal strings.",
                    True,
                    None,
                    disposition="problem",
                )
            )
        qualifiers = [
            ("project", document.get("project")),
            ("build-system", document.get("build-system")),
            ("tool.poetry", tool.get("poetry")),
            ("tool.uv.workspace", uv_workspace if _valid_uv_workspace(uv_workspace) else None),
        ]
        keys: list[tuple[str, str, str | None, str]] = []
        for locator, value in qualifiers:
            if not isinstance(value, dict):
                continue
            key = add_evidence(
                _python_evidence(
                    "manifest",
                    path,
                    locator,
                    f"Python manifest table {locator} is declared.",
                    f"manifest:{root}:{locator}",
                )
            )
            keys.append(key)
            add_finding(
                "python.manifest.declaration",
                "verified",
                root,
                f"Python manifest table {locator} is declared.",
                (key,),
            )
        if keys:
            qualified_roots.add(root)
            component_keys.setdefault(root, []).extend(keys)

    for path in paths:
        if _checkpoint(view):
            break
        if PurePosixPath(path).name not in {"setup.cfg", "tox.ini", ".flake8"}:
            continue
        data = view.read_bytes(path)
        if data is None:
            continue
        if PurePosixPath(path).name == "setup.cfg" and (
            _template_path(path) or _template_content(data)
        ):
            record_template(path)
            continue
        try:
            parsed_ini = _ini_document(data)
        except (UnicodeError, configparser.Error):
            diagnostics.append(
                _DiagnosticCandidate(
                    "python.invalid-configuration",
                    path,
                    "Python INI configuration is invalid.",
                    True,
                    _parent(path),
                    disposition="problem",
                )
            )
            continue
        ini_files[path] = parsed_ini
        if (
            PurePosixPath(path).name == "setup.cfg"
            and parsed_ini.has_section("metadata")
            and parsed_ini.has_section("options")
        ):
            root = _parent(path)
            key = add_evidence(
                _python_evidence(
                    "manifest",
                    path,
                    "metadata+options",
                    "Legacy setup.cfg package metadata and options are declared.",
                    f"manifest:{root}:setup-cfg",
                )
            )
            qualified_roots.add(root)
            component_keys.setdefault(root, []).append(key)
            add_finding(
                "python.manifest.declaration",
                "verified",
                root,
                "Legacy setup.cfg declares a Python package boundary.",
                (key,),
            )

    for path in paths:
        if _checkpoint(view):
            break
        if PurePosixPath(path).name != "setup.py":
            continue
        root = _parent(path)
        key = add_evidence(
            _python_evidence(
                "file-presence",
                path,
                None,
                "A legacy setup.py candidate is present; it was not evaluated.",
                f"setup-py:{root}",
            )
        )
        if root in qualified_roots:
            component_keys.setdefault(root, []).append(key)
            add_finding(
                "python.manifest.declaration",
                "verified",
                root,
                "A setup.py file is present and was not evaluated.",
                (key,),
            )
        else:
            components.append(_ComponentCandidate(root, "package-candidate", (key,)))
            add_finding(
                "python.component.candidate",
                "unknown",
                root,
                "A setup.py candidate is present, but no static Python package declaration was found.",
                (key,),
            )
            diagnostics.append(
                _DiagnosticCandidate(
                    "python.dynamic-manifest-unknown",
                    path,
                    "setup.py was not executed, so its package metadata remains unknown.",
                    False,
                    root,
                    (key,),
                    disposition="limitation",
                )
            )

    requirements_by_parent: dict[str, list[PathCandidate]] = {}
    for candidate in path_candidates:
        if _checkpoint(view):
            break
        if re.fullmatch(r"(?:requirements|constraints).*\.txt", candidate.name, re.IGNORECASE):
            requirements_by_parent.setdefault(candidate.parent, []).append(candidate)
    sorted_qualified_roots = tuple(sorted(qualified_roots))

    for root in sorted_qualified_roots:
        if _checkpoint(view):
            break
        path, document = pyprojects.get(root, ("", {}))
        project_value = document.get("project")
        project = cast(dict[str, object], project_value) if isinstance(project_value, dict) else {}
        tool_value = document.get("tool")
        tool = cast(dict[str, object], tool_value) if isinstance(tool_value, dict) else {}
        has_poetry = isinstance(tool, dict) and isinstance(tool.get("poetry"), dict)
        has_uv = isinstance(tool, dict) and isinstance(tool.get("uv"), dict)
        poetry = cast(dict[str, object], tool["poetry"]) if has_poetry else {}
        uv = cast(dict[str, object], tool["uv"]) if has_uv else {}

        if path:
            for field_name in ("name",):
                if isinstance(project.get(field_name), str):
                    key = add_evidence(
                        _python_evidence(
                            "metadata",
                            path,
                            f"project.{field_name}",
                            f"Python project metadata field {field_name} is declared.",
                            f"metadata:{root}:{field_name}",
                        )
                    )
                    add_finding(
                        "python.metadata.declaration",
                        "verified",
                        root,
                        f"Project {field_name} is {_quoted(project[field_name])}.",
                        (key,),
                    )
            runtime = project.get("requires-python")
            if isinstance(runtime, str):
                record_runtime(root, runtime, path, "project.requires-python", "constraint")
            dynamic = project.get("dynamic")
            if isinstance(dynamic, list):
                for index, value in enumerate(dynamic):
                    if isinstance(value, str):
                        locator = f"project.dynamic[{index}]"
                        key = add_evidence(
                            _python_evidence(
                                "metadata",
                                path,
                                locator,
                                f"Python project field {value} is declared dynamic.",
                                f"dynamic-metadata:{root}:{value}:{index}",
                            )
                        )
                        add_finding(
                            "python.metadata.dynamic",
                            "unknown",
                            root,
                            f"Dynamic project field {_quoted(value)} was not evaluated.",
                            (key,),
                        )
                        diagnostics.append(
                            _DiagnosticCandidate(
                                "python.dynamic-metadata-unknown",
                                path,
                                f"Dynamic project field {_quoted(value)} is declared at {path} "
                                f"[{locator}] and was not evaluated. Next: declare it statically if "
                                "it should be inspected, or retain it as an explicit unknown.",
                                False,
                                root,
                                (key,),
                                disposition="limitation",
                            )
                        )
            dependencies = project.get("dependencies")
            if isinstance(dependencies, list):
                for index, raw in enumerate(dependencies):
                    if isinstance(raw, str):
                        record_dependency(
                            root, raw, path, f"project.dependencies[{index}]", "project"
                        )
            optional = project.get("optional-dependencies")
            if isinstance(optional, dict):
                for group, values in optional.items():
                    if isinstance(values, list):
                        for index, raw in enumerate(values):
                            if isinstance(raw, str):
                                record_dependency(
                                    root,
                                    raw,
                                    path,
                                    _toml_locator(
                                        "project", "optional-dependencies", group, index=index
                                    ),
                                    f"extra:{group}",
                                )
            for table_name in ("scripts", "gui-scripts"):
                table = project.get(table_name)
                if isinstance(table, dict):
                    for name in sorted(key for key in table if isinstance(key, str)):
                        key = add_evidence(
                            _python_evidence(
                                "entry-point",
                                path,
                                _toml_locator("project", table_name, name),
                                f"Install-time entry point {name} is declared.",
                                f"entry-point:{root}:{table_name}:{name}",
                            )
                        )
                        add_finding(
                            "python.entry-point.declaration",
                            "verified",
                            root,
                            f"Install-time entry point {name} is declared.",
                            (key,),
                        )

        groups = document.get("dependency-groups")
        if path and isinstance(groups, dict):
            for group, values in groups.items():
                if isinstance(values, list):
                    for index, raw in enumerate(values):
                        if isinstance(raw, str):
                            record_dependency(
                                root,
                                raw,
                                path,
                                _toml_locator("dependency-groups", group, index=index),
                                f"group:{group}",
                            )

        if path and has_uv:
            record_manager(root, "uv", path, "tool.uv", "uv configuration is declared.")
        if path and has_poetry:
            record_manager(root, "poetry", path, "tool.poetry", "Poetry metadata is declared.")
            poetry_dependencies = poetry.get("dependencies")
            if isinstance(poetry_dependencies, dict):
                for name, value in poetry_dependencies.items():
                    if canonicalize_name(name) == "python":
                        if isinstance(value, str):
                            record_runtime(
                                root,
                                value,
                                path,
                                "tool.poetry.dependencies.python",
                                "constraint",
                            )
                        continue
                    record_dependency(
                        root,
                        name,
                        path,
                        _toml_locator("tool", "poetry", "dependencies", name),
                        "poetry:main",
                    )
            poetry_groups = poetry.get("group")
            if isinstance(poetry_groups, dict):
                for group, group_value in poetry_groups.items():
                    dependencies = (
                        group_value.get("dependencies") if isinstance(group_value, dict) else None
                    )
                    if isinstance(dependencies, dict):
                        for name in dependencies:
                            record_dependency(
                                root,
                                name,
                                path,
                                _toml_locator(
                                    "tool", "poetry", "group", group, "dependencies", name
                                ),
                                f"poetry:{group}",
                            )
            scripts = poetry.get("scripts")
            if isinstance(scripts, dict):
                for name in sorted(key for key in scripts if isinstance(key, str)):
                    key = add_evidence(
                        _python_evidence(
                            "entry-point",
                            path,
                            _toml_locator("tool", "poetry", "scripts", name),
                            f"Legacy Poetry entry point {name} is declared.",
                            f"entry-point:{root}:poetry:{name}",
                        )
                    )
                    add_finding(
                        "python.entry-point.declaration",
                        "verified",
                        root,
                        f"Legacy Poetry entry point {name} is declared.",
                        (key,),
                    )

        workspace = uv.get("workspace") if has_uv else None
        if path and isinstance(workspace, dict):
            workspace_key = add_evidence(
                _python_evidence(
                    "workspace",
                    path,
                    "tool.uv.workspace",
                    "A uv workspace declaration is present.",
                    f"workspace:{root}:uv",
                )
            )
            members = workspace.get("members", [])
            excludes = workspace.get("exclude", [])
            if not _valid_uv_workspace(workspace):
                diagnostics.append(
                    _DiagnosticCandidate(
                        "python.invalid-workspace",
                        path,
                        "uv workspace members and exclusions must be lists of literal strings.",
                        True,
                        root,
                        (workspace_key,),
                        disposition="problem",
                    )
                )
            else:
                component_keys[root].append(workspace_key)
                excluded = cast(list[str], excludes)
                members = cast(list[str], members)
                for index, member in enumerate(members):
                    if _safe_member(root, member.replace("*", "member")) is None:
                        diagnostics.append(
                            _DiagnosticCandidate(
                                "python.invalid-workspace-member",
                                path,
                                "A uv workspace member pattern escapes the repository.",
                                True,
                                root,
                                (workspace_key,),
                                disposition="problem",
                            )
                        )
                        continue
                    matches = []
                    for component_root in _descendant_paths(root, sorted_qualified_roots):
                        if _checkpoint(view):
                            break
                        if (
                            component_root != root
                            and fnmatch.fnmatchcase(
                                component_root, _safe_member(root, member) or member
                            )
                            and not any(
                                fnmatch.fnmatchcase(
                                    component_root, _safe_member(root, item) or item
                                )
                                for item in excluded
                            )
                        ):
                            matches.append(component_root)
                    if not matches:
                        diagnostics.append(
                            _DiagnosticCandidate(
                                "python.missing-workspace-member",
                                path,
                                "A uv workspace member pattern matched no qualifying Python component.",
                                True,
                                root,
                                (workspace_key,),
                                disposition="problem",
                            )
                        )
                    for member_root in sorted(matches):
                        member_key = add_evidence(
                            _python_evidence(
                                "workspace",
                                path,
                                f"tool.uv.workspace.members[{index}]",
                                f"uv workspace membership is declared for {member_root}.",
                                f"workspace-member:{root}:{member_root}",
                            )
                        )
                        add_finding(
                            "python.workspace.member",
                            "verified",
                            member_root,
                            f"Component {member_root} is a declared uv workspace member.",
                            (member_key,),
                        )
                        relationships.append(
                            _RelationshipCandidate(
                                "workspace-member",
                                root,
                                member_root,
                                "verified",
                                (member_key,),
                            )
                        )

        for filename, manager_name in (
            ("uv.lock", "uv"),
            ("uv.toml", "uv"),
            ("poetry.lock", "poetry"),
        ):
            candidate_path = filename if root == "." else f"{root}/{filename}"
            if candidate_path in path_set:
                record_manager(
                    root,
                    manager_name,
                    candidate_path,
                    None,
                    f"{filename} is present.",
                    is_lock=filename.endswith(".lock"),
                )

        python_version = ".python-version" if root == "." else f"{root}/.python-version"
        if python_version in path_set:
            data = view.read_bytes(python_version)
            if data is not None:
                try:
                    values = [line.strip() for line in _decode(data).splitlines() if line.strip()]
                except UnicodeError:
                    diagnostics.append(
                        _DiagnosticCandidate(
                            "python.invalid-runtime-file",
                            python_version,
                            ".python-version is not valid UTF-8.",
                            True,
                            root,
                            disposition="problem",
                        )
                    )
                else:
                    for index, value in enumerate(values):
                        record_runtime(
                            root, value, python_version, f"line:{index + 1}", "selection"
                        )

        for requirement in requirements_by_parent.get(root, ()):
            requirement_path = requirement.path
            name = requirement.name
            record_manager(root, "pip", requirement_path, None, f"{name} is present.")
            data = view.read_bytes(requirement_path)
            if data is None:
                continue
            try:
                lines = _decode(data).splitlines()
            except UnicodeError:
                diagnostics.append(
                    _DiagnosticCandidate(
                        "python.invalid-requirements",
                        requirement_path,
                        "Requirements evidence is not valid UTF-8.",
                        True,
                        root,
                        disposition="problem",
                    )
                )
                continue
            generated = _pip_compile_generated(lines)
            constrained = name.lower().startswith("constraints")
            if generated or constrained:
                continue
            for index, line in enumerate(lines):
                stripped = _strip_requirement_comment(line.strip())
                if not stripped or stripped.startswith(("#", "-")):
                    continue
                record_dependency(root, stripped, requirement_path, f"line:{index + 1}", name)

    for path in paths:
        if _checkpoint(view):
            break
        name = PurePosixPath(path).name
        root = _parent(path)
        if (
            name in {"uv.lock", "uv.toml", "poetry.lock"}
            and root not in qualified_roots
            and not _template_path(path)
        ):
            manager_name = "poetry" if name == "poetry.lock" else "uv"
            key = record_manager(
                root,
                manager_name,
                path,
                None,
                f"Unbound {name} is present.",
                is_lock=name.endswith(".lock"),
            )
            add_finding(
                "python.affiliation.unknown",
                "unknown",
                None,
                f"{name} is present, but its Python component affiliation is unknown.",
                (key,),
            )
            diagnostics.append(
                _DiagnosticCandidate(
                    "python.unbound-evidence",
                    path,
                    "Manager evidence has no qualifying Python manifest at the same root.",
                    False,
                    None,
                    (key,),
                    disposition="limitation",
                )
            )

    tool_files = {
        "pytest.toml": "pytest",
        ".pytest.toml": "pytest",
        "pytest.ini": "pytest",
        "ruff.toml": "ruff",
        ".ruff.toml": "ruff",
        "mypy.ini": "mypy",
        ".mypy.ini": "mypy",
        "pyrightconfig.json": "pyright",
        ".coveragerc": "coverage",
        "tox.toml": "tox",
        ".pre-commit-config.yaml": "pre-commit",
        "alembic.ini": "alembic",
    }
    for path in paths:
        if _checkpoint(view):
            break
        name = PurePosixPath(path).name
        root = _parent(path)
        if name == "conftest.py":
            if _template_path(path):
                continue
            nearest_root = _nearest_ancestor(root, qualified_roots)
            if nearest_root is not None:
                record_tool(nearest_root, "pytest", path, None, "convention")
            continue
        tool_name = tool_files.get(name)
        if tool_name is None or _template_path(path):
            continue
        if name in {"pyrightconfig.json", ".pre-commit-config.yaml"}:
            data = view.read_bytes(path)
            if data is None:
                continue
            try:
                parsed_config: object = (
                    json.loads(_decode(data)) if name.endswith(".json") else _yaml_document(data)
                )
                if not isinstance(parsed_config, dict):
                    raise ValueError
            except (
                UnicodeError,
                json.JSONDecodeError,
                yaml.YAMLError,
                _YamlStructureError,
                ValueError,
            ) as error:
                unsupported = isinstance(error, _YamlStructureError)
                diagnostics.append(
                    _DiagnosticCandidate(
                        (
                            "python.unsupported-configuration"
                            if unsupported
                            else "python.invalid-configuration"
                        ),
                        path,
                        (
                            f"{tool_name} configuration at {path} uses an unsupported YAML "
                            "structure. Next: replace aliases, "
                            "custom tags, or cyclic structures with explicit safe values if this "
                            "configuration should be inspected."
                            if unsupported
                            else f"{tool_name} configuration at {path} could not be parsed. "
                            "Next: correct its syntax or encoding and scan again."
                        ),
                        True,
                        root if root in qualified_roots else None,
                        disposition="limitation" if unsupported else "problem",
                    )
                )
                continue
        record_tool(root, tool_name, path, None)

    for root, (path, document) in pyprojects.items():
        tool_value = document.get("tool")
        tool = cast(dict[str, object], tool_value) if isinstance(tool_value, dict) else {}
        tables = {
            "pytest": ("pytest", "pytest.ini_options"),
            "ruff": ("ruff",),
            "black": ("black",),
            "mypy": ("mypy",),
            "pyright": ("pyright",),
            "coverage": ("coverage",),
            "tox": ("tox",),
        }
        for tool_name, names in tables.items():
            if any(isinstance(tool.get(name), dict) for name in names):
                locator = next(name for name in names if isinstance(tool.get(name), dict))
                record_tool(root, tool_name, path, f"tool.{locator}")

    for path, parser in ini_files.items():
        root = _parent(path)
        if PurePosixPath(path).name == "tox.ini" and any(
            section == "tox" or section.startswith("testenv") for section in parser.sections()
        ):
            record_tool(root, "tox", path, "tox/testenv")
        sections = {
            "pytest": ("pytest", "tool:pytest"),
            "flake8": ("flake8",),
            "pycodestyle": ("pycodestyle",),
            "mypy": ("mypy",),
        }
        for tool_name, names in sections.items():
            for section in names:
                if parser.has_section(section):
                    record_tool(root, tool_name, path, section)

    component_roots = frozenset(qualified_roots - generic_component_paths)

    def component_for(directory: str) -> str | None:
        return _nearest_ancestor(directory, component_roots)

    def workflow_directory(value: object) -> str | None:
        if not isinstance(value, str) or "${{" in value or "\\" in value:
            return None
        stripped = value.strip()
        if stripped in {"", ".", "./"}:
            return "."
        return _safe_member(".", stripped[2:] if stripped.startswith("./") else stripped)

    def owned_directory(
        directory: object, ownership: dict[str, bool | None], checkout_seen: bool
    ) -> str | None:
        normalized = workflow_directory(directory)
        if normalized is None:
            return None
        if not checkout_seen:
            return normalized
        candidates = [
            path
            for path in ownership
            if path == "." or normalized == path or normalized.startswith(f"{path}/")
        ]
        if not candidates:
            return None
        owner = max(candidates, key=len)
        if ownership[owner] is not True:
            return None
        if owner == ".":
            return normalized
        remainder = normalized[len(owner) :].lstrip("/")
        return remainder or "."

    def emit_command(path: str, locator: str, command: str, subject: str) -> None:
        item = _python_evidence(
            "ci-command",
            path,
            locator,
            "A literal CI command is declared.",
            f"ci-command:{path}:{locator}:{hashlib.sha256(command.encode()).hexdigest()}",
        )
        key = add_evidence(item)
        if _contains_literal_credential(command):
            add_finding(
                "python.ci.command",
                "unknown",
                subject,
                "A CI command is declared, but its text was withheld because it resembles credential material.",
                (key,),
            )
            diagnostics.append(
                _DiagnosticCandidate(
                    "python.sensitive-command-redacted",
                    path,
                    f"A CI command at {path} [{locator}] contains a credential-shaped literal that "
                    "may be sensitive, so its value was withheld. Next: review whether it is "
                    "intentional non-sensitive test data; if it is sensitive, replace it with an "
                    "authorized CI secret reference and scan again.",
                    False,
                    subject,
                    (key,),
                    disposition="notice",
                )
            )
        else:
            add_finding(
                "python.ci.command",
                "verified",
                subject,
                f"CI declares command {_quoted(command)}.",
                (key,),
            )

    def emit_dynamic_command(path: str, locator: str, subject: str) -> None:
        item = _python_evidence(
            "ci-command",
            path,
            locator,
            "A dynamic CI command expression is declared.",
            f"dynamic-ci-command:{path}:{locator}",
        )
        key = add_evidence(item)
        add_finding(
            "python.ci.command.dynamic",
            "unknown",
            subject,
            "A dynamic CI command expression was not evaluated.",
            (key,),
        )
        diagnostics.append(
            _DiagnosticCandidate(
                "python.dynamic-ci-command-unknown",
                path,
                f"A CI run value at {path} [{locator}] consists only of a workflow expression. "
                "Next: inspect the expression's workflow inputs when the concrete command is needed.",
                False,
                subject,
                (key,),
                disposition="limitation",
            )
        )

    for path in paths:
        if _checkpoint(view):
            break
        if not (
            (path.startswith(".gitea/workflows/") or path.startswith(".github/workflows/"))
            and path.endswith((".yml", ".yaml"))
        ):
            continue
        data = view.read_bytes(path)
        if data is None:
            continue
        try:
            workflow_document = _yaml_document(data)
            if not isinstance(workflow_document, dict):
                raise _YamlStructureError
        except (UnicodeError, yaml.YAMLError, _YamlStructureError):
            diagnostics.append(
                _DiagnosticCandidate(
                    "python.invalid-ci-workflow",
                    path,
                    "CI workflow YAML is invalid.",
                    True,
                    disposition="problem",
                )
            )
            continue
        jobs = workflow_document.get("jobs")
        if not isinstance(jobs, dict):
            continue
        for job_name, job in jobs.items():
            if not isinstance(job, dict):
                continue
            matrix = job.get("strategy")
            matrix = matrix.get("matrix") if isinstance(matrix, dict) else {}
            steps = job.get("steps")
            if not isinstance(steps, list):
                continue
            defaults = job.get("defaults")
            defaults = defaults.get("run") if isinstance(defaults, dict) else {}
            job_directory = (
                defaults.get("working-directory", ".") if isinstance(defaults, dict) else "."
            )
            ownership: dict[str, bool | None] = {}
            checkout_seen = False
            for index, step in enumerate(steps):
                if not isinstance(step, dict):
                    continue
                uses = step.get("uses")
                with_values = step.get("with")
                if isinstance(uses, str) and uses.startswith("actions/checkout@"):
                    checkout_seen = True
                    checkout_path = (
                        with_values.get("path", ".") if isinstance(with_values, dict) else "."
                    )
                    normalized_checkout = workflow_directory(checkout_path)
                    repository = (
                        with_values.get("repository") if isinstance(with_values, dict) else None
                    )
                    if normalized_checkout is not None:
                        ownership[normalized_checkout] = (
                            True
                            if repository is None
                            else False
                            if isinstance(repository, str) and "${{" not in repository
                            else None
                        )
                directory = step.get("working-directory", job_directory)
                repository_directory = owned_directory(directory, ownership, checkout_seen)
                subject = (
                    component_for(repository_directory)
                    if repository_directory is not None
                    else None
                )
                command = step.get("run")
                if isinstance(command, str) and subject is not None:
                    locator = _pointer("jobs", job_name, "steps", index, "run")
                    if _expression_only(command):
                        emit_dynamic_command(path, locator, subject)
                    else:
                        emit_command(path, locator, command, subject)
                version = (
                    with_values.get("python-version") if isinstance(with_values, dict) else None
                )
                if (
                    isinstance(uses, str)
                    and uses.startswith("actions/setup-python@")
                    and isinstance(version, str)
                    and subject is not None
                ):
                    reference = _matrix_reference(version)
                    resolved = (
                        _matrix_values(
                            matrix,
                            reference,
                            ("jobs", job_name, "strategy", "matrix"),
                        )
                        if reference is not None
                        else ()
                    )
                    if resolved:
                        for value in resolved:
                            record_runtime(subject, value.value, path, value.locator, "selection")
                    elif "${{" not in version:
                        record_runtime(
                            subject,
                            version,
                            path,
                            _pointer("jobs", job_name, "steps", index, "with", "python-version"),
                            "selection",
                        )
                    else:
                        locator = _pointer(
                            "jobs", job_name, "steps", index, "with", "python-version"
                        )
                        key = add_evidence(
                            _python_evidence(
                                "runtime",
                                path,
                                locator,
                                "A dynamic setup-python runtime expression is declared.",
                                f"dynamic-ci-runtime:{path}:{locator}",
                            )
                        )
                        add_finding(
                            "python.runtime.dynamic",
                            "unknown",
                            subject,
                            "A dynamic setup-python runtime expression was not evaluated.",
                            (key,),
                        )
                        diagnostics.append(
                            _DiagnosticCandidate(
                                "python.dynamic-ci-runtime-unknown",
                                path,
                                f"A dynamic or unsupported setup-python runtime expression at {path} "
                                f"[{locator}] was not evaluated. Next: use a literal version, a direct "
                                "static matrix property, or inspect the unsupported expression manually.",
                                False,
                                subject,
                                (key,),
                                disposition="limitation",
                            )
                        )

    if ".gitlab-ci.yml" in path_set and component_for(".") is not None:
        visited: set[str] = set()

        def visit_gitlab(path: str, depth: int) -> None:
            if path in visited:
                diagnostics.append(
                    _DiagnosticCandidate(
                        "python.ci-include-cycle",
                        path,
                        "A GitLab local include cycle was not expanded.",
                        False,
                        ".",
                        disposition="problem",
                    )
                )
                return
            if depth > 16:
                diagnostics.append(
                    _DiagnosticCandidate(
                        "python.ci-include-depth",
                        path,
                        "GitLab local include nesting exceeded the supported bound.",
                        True,
                        ".",
                        disposition="limitation",
                    )
                )
                return
            visited.add(path)
            data = view.read_bytes(path)
            if data is None:
                return
            try:
                document = _yaml_document(data)
                if not isinstance(document, dict):
                    raise _YamlStructureError
            except (UnicodeError, yaml.YAMLError, _YamlStructureError):
                diagnostics.append(
                    _DiagnosticCandidate(
                        "python.invalid-ci-workflow",
                        path,
                        "GitLab CI YAML is invalid.",
                        True,
                        ".",
                        disposition="problem",
                    )
                )
                return
            includes = document.get("include", [])
            includes = includes if isinstance(includes, list) else [includes]
            for index, include in enumerate(includes):
                local = (
                    include
                    if isinstance(include, str)
                    else include.get("local")
                    if isinstance(include, dict)
                    else None
                )
                if isinstance(local, str) and "*" not in local and "$" not in local:
                    normalized = local.lstrip("/")
                    if _safe_member(".", normalized) is None or normalized not in path_set:
                        diagnostics.append(
                            _DiagnosticCandidate(
                                "python.invalid-ci-include",
                                path,
                                "A GitLab local include is missing or escapes the repository.",
                                True,
                                ".",
                                disposition="problem",
                            )
                        )
                    else:
                        visit_gitlab(normalized, depth + 1)
                elif include:
                    key = add_evidence(
                        _python_evidence(
                            "ci-include",
                            path,
                            _pointer("include", index),
                            "An external or dynamic GitLab include remains unexpanded.",
                            f"external-include:{path}:{index}",
                        )
                    )
                    add_finding(
                        "python.ci.external-include",
                        "unknown",
                        ".",
                        "An external or dynamic GitLab include was not expanded.",
                        (key,),
                    )
                    diagnostics.append(
                        _DiagnosticCandidate(
                            "python.external-ci-include",
                            path,
                            "External, component, project, template, and dynamic includes are not fetched.",
                            False,
                            ".",
                            (key,),
                            disposition="limitation",
                        )
                    )
            reserved = {
                "include",
                "stages",
                "variables",
                "workflow",
                "default",
                "image",
                "services",
                "before_script",
                "after_script",
                "cache",
                "pages",
                "interruptible",
            }

            def commands(value: object, locator: tuple[object, ...]) -> None:
                values = value if isinstance(value, list) else [value]
                for index, command in enumerate(values):
                    if isinstance(command, str):
                        emit_command(path, _pointer(*locator, index), command, ".")
                    elif isinstance(command, dict) and isinstance(command.get("run"), str):
                        emit_command(
                            path, _pointer(*locator, index, "run"), cast(str, command["run"]), "."
                        )

            for field_name in ("before_script", "after_script"):
                if field_name in document:
                    commands(document[field_name], (field_name,))
            for job_name, job in document.items():
                if job_name in reserved or job_name.startswith(".") or not isinstance(job, dict):
                    continue
                for field_name in ("before_script", "script", "after_script", "run"):
                    if field_name in job:
                        commands(job[field_name], (job_name, field_name))

        visit_gitlab(".gitlab-ci.yml", 0)

    for root in sorted_qualified_roots:
        if _checkpoint(view):
            break
        components.append(
            _ComponentCandidate(
                root,
                "workspace"
                if any(key[2] == "tool.uv.workspace" for key in component_keys[root])
                else "package",
                tuple(component_keys[root]),
                "python",
            )
        )
        if root in generic_component_paths:
            continue
        add_finding(
            "python.component.verified",
            "verified",
            root,
            (
                "A Python component is declared at the repository root."
                if root == "."
                else f"A Python component is declared at {root}."
            ),
            tuple(component_keys[root]),
        )

    for root, families in manager_locks.items():
        if len(families) > 1:
            conflict_keys = tuple(key for values in families.values() for key in values)
            details = "; ".join(
                f"{name}: {', '.join(sorted(key[1] for key in keys))}"
                for name, keys in sorted(families.items())
            )
            diagnostics.append(
                _DiagnosticCandidate(
                    "python.manager-conflict",
                    root,
                    f"Competing Python lock families are present for component {_quoted(root)}: "
                    f"{details}. No manager preference was selected. Next: keep both lock families "
                    "only if this is intentional; otherwise remove or regenerate the obsolete lock.",
                    False,
                    root if root in qualified_roots else None,
                    conflict_keys,
                    disposition="problem",
                )
            )
    for root, declarations in runtimes.items():
        constraints: list[tuple[_RuntimeCandidate, SpecifierSet]] = []
        selections: list[tuple[_RuntimeCandidate, Version]] = []
        for declaration in declarations:
            try:
                if declaration.role == "constraint":
                    constraints.append((declaration, SpecifierSet(declaration.value)))
                else:
                    selections.append((declaration, Version(declaration.value)))
            except (InvalidSpecifier, InvalidVersion):
                continue
        conflicts = [
            (selection, constraint)
            for selection, version in selections
            for constraint, specifier in constraints
            if version not in specifier
        ]
        if conflicts:
            involved = sorted(
                {item for conflict in conflicts for item in conflict},
                key=lambda item: (item.path, item.locator, item.role, item.value),
            )
            details = "; ".join(
                f"{item.path} [{item.locator}] "
                f"{'declares the supported range' if item.role == 'constraint' else 'selects'} "
                f"{_quoted(item.value)}"
                for item in involved
            )
            conflict_keys = tuple(item.evidence_key for item in involved)
            diagnostics.append(
                _DiagnosticCandidate(
                    "python.runtime-conflict",
                    root,
                    f"Python runtime declarations conflict for component {_quoted(root)}: {details}. "
                    "At least one selected version does not satisfy a declared supported range. "
                    "Next: choose a selected Python version within the supported range, or update "
                    "the range if support for that version is intentional.",
                    False,
                    root,
                    conflict_keys,
                    disposition="problem",
                )
            )
    for root, by_tool in tools.items():
        if root not in qualified_roots:
            continue
        for tool_name, keys in by_tool.items():
            locations = {key[1] for key in keys}
            if len(locations) > 1:
                diagnostics.append(
                    _DiagnosticCandidate(
                        "python.tool-configuration-conflict",
                        root,
                        f"Multiple {tool_name} evidence locations are present; none was selected.",
                        False,
                        root if root in qualified_roots else None,
                        tuple(keys),
                        disposition="problem",
                    )
                )

    return DetectionResult(
        evidence=tuple(evidence),
        components=tuple(components),
        findings=tuple(findings),
        diagnostics=tuple(diagnostics),
        relationships=tuple(relationships),
    )
